aws_region         = "us-east-1"
environment        = "production"
project            = "Session19-Cloud-Terraform"
vpc_cidr           = "10.30.0.0/16"
public_subnet_cidr = "10.30.1.0/24"
instance_type      = "t3.micro"
bucket_name        = "devops-session19-cloud-bucket-2026"
