apiVersion: v1
kind: Service
metadata:
  name: monitoring-demo-service
  namespace: default
  labels:
    app: monitoring-demo-app
spec:
  type: NodePort
  selector:
    app: monitoring-demo-app
  ports:
    - name: http-metrics
      port: 8000
      targetPort: 8000
      nodePort: 30800
